param([switch]$SkipBuild)
$ErrorActionPreference = 'Stop'
$projectRoot = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
Set-Location -LiteralPath $projectRoot
$manifest = Get-Content -LiteralPath (Join-Path $projectRoot 'Cargo.toml') -Raw
$versionMatch = [regex]::Match($manifest, '(?m)^version\s*=\s*"(\d+\.\d+\.\d+)"')
if (-not $versionMatch.Success) { throw 'No se encontró la versión de Cargo' }
$version = [version]$versionMatch.Groups[1].Value
$tag = '{0}.{1}' -f $version.Major, $version.Minor
# Never increment the version or preserve numbered copies automatically.
if (-not $SkipBuild) {
    cargo build --locked --release --bins
    if ($LASTEXITCODE -ne 0) { throw 'Falló la compilación' }
}
$built = Join-Path $projectRoot 'target\release\whakoom-desktop.exe'
if (-not (Test-Path -LiteralPath $built)) { throw 'Falta el ejecutable compilado' }
$distRoot = Join-Path $projectRoot 'dist'
[IO.Directory]::CreateDirectory($distRoot) | Out-Null
$prefix = "Whakoom-Desktop-$tag"
$exe = "$prefix.exe"
Copy-Item -LiteralPath $built -Destination (Join-Path $distRoot $exe) -Force
$docs = @('README.md','LICENSE','THIRD_PARTY_NOTICES.md','CHANGELOG.md','VALIDATION.md')
foreach ($file in $docs) { Copy-Item -LiteralPath (Join-Path $projectRoot $file) -Destination (Join-Path $distRoot $file) -Force }
Add-Type -AssemblyName System.IO.Compression
Add-Type -AssemblyName System.IO.Compression.FileSystem
function Write-Package([string]$zipPath, [string]$basePath, [string[]]$files, [string]$entryPrefix) {
    $stream = [IO.File]::Create($zipPath)
    $archive = [IO.Compression.ZipArchive]::new($stream, [IO.Compression.ZipArchiveMode]::Create)
    try {
        foreach ($relative in $files) {
            $source = [IO.Path]::GetFullPath((Join-Path $basePath $relative))
            if (-not $source.StartsWith($basePath + '\', [StringComparison]::OrdinalIgnoreCase)) { throw 'Archivo fuera del proyecto' }
            $entry = $entryPrefix + $relative.Replace('\','/')
            [IO.Compression.ZipFileExtensions]::CreateEntryFromFile($archive, $source, $entry, [IO.Compression.CompressionLevel]::Optimal) | Out-Null
        }
    } finally { $archive.Dispose(); $stream.Dispose() }
}
$sourceFiles = @(git -c core.quotepath=false ls-files --cached --others --exclude-standard)
if ($LASTEXITCODE -ne 0 -or $sourceFiles.Count -eq 0) { throw 'No se pudo listar el código fuente' }
foreach ($file in $sourceFiles) {
    if ($file -match '(^|/)(target|dist|\.git|libraries|covers|pages|webview)/|\.dpapi$|^settings\.json$|^preview.*\.png$') { throw "Dato privado o artefacto incluido: $file" }
}
Write-Package (Join-Path $distRoot "$prefix-source.zip") $projectRoot $sourceFiles 'whakoom-desktop/'
Write-Package (Join-Path $distRoot "$prefix-portable.zip") $distRoot (@($exe) + $docs) ''
# Only remove releases generated by this project, after the current packages exist.
foreach ($previous in Get-ChildItem -LiteralPath $distRoot -File) {
    if ($previous.Name -match '^Whakoom-Desktop-\d+\.\d+(?:-portable|-source)?\.(?:exe|zip)$' -and
        $previous.Name -notin @($exe,"$prefix-portable.zip","$prefix-source.zip")) {
        $resolved = [IO.Path]::GetFullPath($previous.FullName)
        if ([IO.Path]::GetDirectoryName($resolved) -ne $distRoot) { throw 'Distribución fuera del proyecto' }
        Remove-Item -LiteralPath $resolved -Force
    }
}
$hashes = foreach ($file in Get-ChildItem -LiteralPath $distRoot -File | Where-Object { $_.Extension -in '.exe','.zip','.AppImage' }) {
    $hash = (Get-FileHash -LiteralPath $file.FullName -Algorithm SHA256).Hash.ToLowerInvariant()
    "$hash  $($file.Name)"
}
[IO.File]::WriteAllLines((Join-Path $distRoot 'SHA256SUMS.txt'), [string[]]$hashes, [Text.UTF8Encoding]::new($false))
Write-Output "Actualizado $exe, portable y código fuente ($($sourceFiles.Count) archivos)."
